### PR TITLE
Create big-bird-mnk-15

### PR DESCRIPTION
**Pull request by B1gBird**
Big Bird's season 15 picks

### CODE REVIEW

**Comment by YamazakiRobert** [comment]
@B1gBird can you unificate your 3 Wishlist? some of them have rolls with differences

**Comment by B1gBird** [comment]
Shoot okay I was worried about that. I couldn't figure out how to delete the first one but if it tells you which one is newer its the newest one

**Comment by B1gBird** [comment]
If you were just talking about the s15 ones that is

**Comment by YamazakiRobert** [comment]
@B1gBird the previous pull had a issue https://github.com/LittleLightForDestiny/littlelight_wishlists/pull/11
a think if you unified all your lists are a better move to don't have discrepancies on all of them (at least non sunset and s14 have some)

**Comment by joaopmarquesini** [comment]
closing in favor of newer one

**Pull request closed without merging**
